const fs = require('fs');
const path = require('path');

function updateSongs(songsDir, outputFile) {
    if (!fs.existsSync(songsDir)) {
        fs.mkdirSync(songsDir, { recursive: true });
    }

    // Get all music files
    const files = fs.readdirSync(songsDir).filter(f =>
        f.endsWith('.mp3') || f.endsWith('.wav') || f.endsWith('.m4a') || f.endsWith('.ogg')
    );

    const content = `// Auto-generated by update-songs.js\nwindow.LOCAL_SONGS = ${JSON.stringify(files, null, 4)};\n`;

    fs.writeFileSync(outputFile, content);
    return files.length;
}

if (require.main === module) {
    const songsDir = path.join(__dirname, 'public', 'assets', 'songs');
    const outputFile = path.join(__dirname, 'public', 'songs-data.js');
    const count = updateSongs(songsDir, outputFile);
    console.log(`Updated music list with ${count} songs.`);
}

module.exports = { updateSongs };
