const { test, describe, beforeEach, afterEach } = require('node:test');
const assert = require('node:assert');
const fs = require('fs');
const path = require('path');
const os = require('os');
const { updateSongs } = require('./update-songs');

describe('updateSongs', () => {
    let tempDir;
    let songsDir;
    let outputFile;

    beforeEach(() => {
        tempDir = fs.mkdtempSync(path.join(os.tmpdir(), 'update-songs-test-'));
        songsDir = path.join(tempDir, 'songs');
        outputFile = path.join(tempDir, 'songs-data.js');
    });

    afterEach(() => {
        fs.rmSync(tempDir, { recursive: true, force: true });
    });

    test('should create songs directory if it does not exist', () => {
        assert.strictEqual(fs.existsSync(songsDir), false);
        updateSongs(songsDir, outputFile);
        assert.strictEqual(fs.existsSync(songsDir), true);
    });

    test('should identify files with supported extensions', () => {
        fs.mkdirSync(songsDir);
        const supportedFiles = ['song1.mp3', 'song2.wav', 'song3.m4a', 'song4.ogg'];
        supportedFiles.forEach(file => fs.writeFileSync(path.join(songsDir, file), ''));

        const count = updateSongs(songsDir, outputFile);

        assert.strictEqual(count, supportedFiles.length);
        const content = fs.readFileSync(outputFile, 'utf8');
        supportedFiles.forEach(file => {
            assert.ok(content.includes(file), `Expected ${file} to be in the output`);
        });
    });

    test('should ignore unsupported file extensions', () => {
        fs.mkdirSync(songsDir);
        fs.writeFileSync(path.join(songsDir, 'test.txt'), '');
        fs.writeFileSync(path.join(songsDir, 'image.png'), '');
        fs.writeFileSync(path.join(songsDir, 'song1.mp3'), '');

        const count = updateSongs(songsDir, outputFile);

        assert.strictEqual(count, 1);
        const content = fs.readFileSync(outputFile, 'utf8');
        assert.ok(content.includes('song1.mp3'));
        assert.ok(!content.includes('test.txt'));
        assert.ok(!content.includes('image.png'));
    });

    test('should handle empty directory', () => {
        fs.mkdirSync(songsDir);
        const count = updateSongs(songsDir, outputFile);
        assert.strictEqual(count, 0);
        const content = fs.readFileSync(outputFile, 'utf8');
        assert.ok(content.includes('window.LOCAL_SONGS = [];'));
    });

    test('should write correct output format', () => {
        fs.mkdirSync(songsDir);
        fs.writeFileSync(path.join(songsDir, 'song.mp3'), '');
        updateSongs(songsDir, outputFile);
        const content = fs.readFileSync(outputFile, 'utf8');
        const expectedPrefix = '// Auto-generated by update-songs.js\nwindow.LOCAL_SONGS = [';
        assert.ok(content.startsWith(expectedPrefix));
    });
});
